services:
  - type: web
    name: capsera-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    # Discord bot specific settings
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
